EventManagement/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('events/',include('events.urls')),
    path('users/', include('users.urls')),
    path('tickets/', include('tickets.urls'))

]

events/urls.py
from django.contrib import admin
from django.urls import path
from events import views


urlpatterns = [
    path('', views.display_events, name="display_events"),
    path('create_event/', views.create_event,name="create_event"),
    path('my_events/', views.my_events, name="my_events"),

]

tickets/urls.py
from django.urls import path
from tickets import views


urlpatterns = [
    path('bookingId-<slug:eventId>/', views.bookTicket, name="bookTicket"),
]

users/urls.py
from django.urls import path
from users import views


urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login_view, name="login_view"),
    path('logout/', views.logout_view, name="logout_view"),

]

events/models.py
from djongo import models

class Event(models.Model):
    _id = models.ObjectIdField(primary_key=True)
    createdBy=models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    date = models.DateField()
    location = models.CharField(max_length=100)
    time = models.TimeField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        db_table='Events'


# Create your models here.

tickets/models.py
from djongo import models


# Create your models here.

class Tickets(models.Model):
    _id = models.ObjectIdField(primary_key=True)
    bookedBy = models.CharField(max_length=100)
    eventId = models.CharField(max_length=100)

    class Meta:
        db_table = 'Tickets'

users/models.py
from djongo import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import AbstractUser, Group, Permission

# class CustomUser(AbstractUser):
#     # pass
#     # Your custom fields and methods here
#
#     groups = models.ManyToManyField(
#         Group,
#         verbose_name=_('groups'),
#         blank=True,
#         help_text=_('The groups this user belongs to.'),
#         related_name='customuser_set'  # Add a custom related name
#     )
#     user_permissions = models.ManyToManyField(
#         Permission,
#         verbose_name=_('user permissions'),
#         blank=True,
#         help_text=_('Specific permissions for this user.'),
#         related_name='customuser_set'  # Add a custom related name
#     )



class Users(models.Model):
    _id = models.ObjectIdField(primary_key=True)
    email = models.EmailField(max_length=100)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=100)

    def __str__(self):
        return str(self._id)

    class Meta:
        db_table = 'Users'

events/forms.py
from django import forms
from .models import Event

class EventCreationForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'date', 'time', 'location', 'description']


"""
Creating a forms.py file in Django serves multiple purposes and provides several benefits:

Separation of Concerns: Keeping form-related code separate from views and models helps maintain a clean and organized code structure. The forms.py file acts as a central place to define all the forms associated with your Django app.

Form Validation and Data Cleaning: Django forms provide built-in validation capabilities, allowing you to define rules and constraints for user input. By defining a form class, you can specify fields, their types, and validation rules. Django automatically handles form validation, ensuring that the submitted data meets the specified requirements. This helps prevent incorrect or malicious data from being saved to the database.

Reusable Forms: By defining forms in a separate file, you can easily reuse them across multiple views or even different apps within your project. This promotes code reusability and reduces duplication.

Convenience and Flexibility: Django forms provide various types of fields (e.g., CharField, DateField, BooleanField, etc.) and widgets (e.g., TextInput, CheckboxInput, Select, etc.), making it easier to handle different types of user input. The forms also offer built-in HTML rendering and error handling, saving you time and effort in creating and managing form elements manually in your templates.

Overall, using a forms.py file helps maintain a modular and structured codebase, ensures proper data validation, and simplifies form handling in your Django project.
"""

users/forms.py
from django import forms
from .models import Users


class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = '__all__'


class LoginForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = ['email', 'password']

events/views.py
from django.shortcuts import render, redirect
from .forms import EventCreationForm
from .models import Event
from users.is_loggedin import login_required
from django.http import HttpResponse


@login_required
def create_event(request):
    if request.method == 'POST':
        form = EventCreationForm(request.POST)
        if form.is_valid():
            event = Event(
                createdBy=request.session.get('id'),
                name=form.cleaned_data['name'],
                date=form.cleaned_data['date'],
                location=form.cleaned_data['location'],
                time=form.cleaned_data['time'],
                description=form.cleaned_data['description']
            )
            event.save()
            return render(request, 'success.html')  # Display a success page
    else:
        form = EventCreationForm()
    return render(request, 'create_event.html', {'form': form})


def display_events(request):
    events_list = Event.objects.all()
    for event in events_list:
        event.id=str(event._id)
    return render(request, 'display_events.html', {'events_list': events_list})

def my_events(request):
    myEventsList=Event.objects.filter(createdBy=request.session['id'])
    print(myEventsList)

    return HttpResponse("printed")

tickets/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Tickets

# Create your views here.

def bookTicket(request, eventId):
    ticket= Tickets(
        eventId=eventId,
        bookedBy=request.session.get('id')
    )
    ticket.save()
    return HttpResponse(eventId)

users/views.py
from django.http import HttpResponse
from django.contrib.auth import authenticate, get_user_model, login
from django.shortcuts import render, redirect
from .forms import RegistrationForm, LoginForm
from .models import Users


def register(request):
    request.session.flush()
    if request.method == 'POST':
        print(request.session.is_empty())
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = Users(
                email=form.cleaned_data['email'],
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],

            )
            user.save()
            request.session['id']=str(user._id)
            request.session['email'] = user.email
            request.session['username'] = user.username

            print(request.session.is_empty())

            return redirect('display_events')
    else:
        form = RegistrationForm()

    return render(request, 'register.html', {'form': form})


def login_view(request):
    print(request.session.is_empty())
    if request.method == 'POST':
        form = LoginForm(request.POST)
        # print(form)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = Users.objects.filter(email=email).first()
            if user is not None and user.password==password:
                request.session['id']=str(user._id)
                print(request.session.get('id'))
                request.session['email'] = user.email
                request.session['username'] = user.username
                return redirect('display_events')
            else:
                error_message = 'Invalid username or password'
                print(error_message)
                return render(request, 'login.html', {'form': form, 'error_message': error_message})
        else:
            print("Invalid form")
    else:

        form = LoginForm()

    return render(request, 'login.html', {'form': form})


def logout_view(request):
    request.session.flush()
    return redirect('login_view')

events/templates/create_event.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    <form method="POST" action="{% url 'create_event' %}">
        {% csrf_token %}
        <label for="id_name">Event Name:</label>
        <input type="text" name="name" id="id_name" required>
        <br>
        <label for="id_date">Date:</label>
        <input type="date" name="date" id="id_date" required>
        <br>
        <label for="id_location">Location:</label>
        <input type="text" name="location" id="id_location" required>
        <br>
        <label for="id_time">Time:</label>
        <input type="time" name="time" id="id_time" required>
        <br>
        <label for="id_description">Description:</label>
        <textarea name="description" id="id_description" required></textarea>
        <br>
        <input type="submit" value="Create Event">
    </form>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

events/templates/display_events.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    {% for event in events_list %}
    <li>
        <strong>{{ event.name }}</strong><br>
        Date: {{ event.date }}<br>
        Location: {{ event.location }}<br>
        Venue: {{ event.venue }}<br>
        Description: {{ event.description }}
    </li>
    <button><a href="../tickets/bookingId-{{event.id}}">Book Now</a></button>
    {% endfor %}

    <button><a href="{% url 'create_event' %}">Create Event</a> </button>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

events/templates/success.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    <h2>Event Created Successfully!</h2>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

users/templates/login.html
<!DOCTYPE html>
{% load static %}
<!-- Coding By CodingNepal - codingnepalweb.com -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
   </head>
<body>
  <div class="wrapper">
    <h2>Login</h2>
    <form method="POST" action="{% url 'login_view' %}">
      {% csrf_token %}
      <div class="input-box">
        <input type="email" name="email" placeholder="Enter your email" required>
      </div>
      <div class="input-box">
        <input type="password" name="password" placeholder="Create password" required>
      </div>
      <div class="input-box button">
        <input type="Submit" value="Login Now">
      </div>
      <div class="text">
        <h3>Don't have an account? <a href="{% url 'register' %}">Signup now</a></h3>
      </div>
    </form>
  </div>
</body>
</html>

users/templates/register.html
<!DOCTYPE html>
{% load static %}
<!-- Coding By CodingNepal - codingnepalweb.com -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Registration or Sign Up </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
   </head>
<body>
  <div class="wrapper">
    <h2>Registration</h2>
    <form method="POST" action="{% url 'register' %}">
      {% csrf_token %}
      <div class="input-box">
        <input type="text" name="username" placeholder="Enter your name" required>
      </div>
      <div class="input-box">
        <input type="text" name="email" placeholder="Enter your email" required>
      </div>
      <div class="input-box">
        <input type="password" name="password" placeholder="Create password" required>
      </div>
      <div class="policy">
        <input type="checkbox">
        <h3>I accept all terms & condition</h3>
      </div>
      <div class="input-box button">
        <input type="Submit" value="Register Now">
      </div>
      <div class="text">
        <h3>Already have an account? <a href="{% url 'login_view' %}">Login now</a></h3>
      </div>
    </form>
  </div>
</body>
</html>